spring.datasource.url=jdbc:postgresql://localhost:5432/user-test
spring.datasource.username=postgres
spring.datasource.password=ROOT

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Kafka Producer
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
spring.kafka.producer.acks=all
spring.kafka.producer.properties.delivery.timeout.ms=20000
spring.kafka.producer.properties.linger.ms=0
spring.kafka.producer.properties.request.timeout.ms=10000

# Resilience4j: Circuit Breaker ??? Kafka
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=30s
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=5
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.configs.default.recordExceptions=org.springframework.kafka.core.KafkaException,\
  java.net.ConnectException,\
  org.apache.kafka.common.errors.TimeoutException
resilience4j.circuitbreaker.configs.default.ignoreExceptions=java.lang.IllegalArgumentException,\
  com.example.projectTest.exception.DuplicateEmailException

# ????????? CB ??? Kafka-?????????
resilience4j.circuitbreaker.instances.kafkaProducer.baseConfig=default


# Retry ??? Kafka (????????? CB)
resilience4j.retry.instances.kafkaRetry.maxAttempts=3
resilience4j.retry.instances.kafkaRetry.waitDuration=5s
resilience4j.retry.instances.kafkaRetry.enableExponentialBackoff=true
resilience4j.retry.instances.kafkaRetry.exponentialBackoffMultiplier=2
resilience4j.retry.instances.kafkaRetry.retryExceptions=org.springframework.kafka.core.KafkaException,\
  java.net.ConnectException,\
  org.apache.kafka.common.errors.TimeoutException